/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrame;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

public class PanelQuanLyHangTonKho extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyHangTonKho
     */
    GridBagLayout layout=new GridBagLayout();
    PanelQuanLyHangTonKho_NhapKho  panelNhapKho;
    PanelQuanLyHangTonKho_XuatKho panelXuatKho;
    public PanelQuanLyHangTonKho() {
        initComponents();
        panelNhapKho=new PanelQuanLyHangTonKho_NhapKho();
        panelXuatKho=new PanelQuanLyHangTonKho_XuatKho();
        layoutQuanLyHangTonKho.setLayout(layout);
        //them 2 panel vao grid
        GridBagConstraints grid=new GridBagConstraints();
        grid.gridx=0;
        grid.gridy=0;
        layoutQuanLyHangTonKho.add(panelNhapKho,grid);
        grid.gridx=0;
        grid.gridy=0;
        layoutQuanLyHangTonKho.add(panelXuatKho,grid);
        grid.gridx=0;
        grid.gridy=0;
        panelXuatKho.setVisible(false);
        panelNhapKho.setVisible(true);//cho hien thi giao dien nay dau tien
        btnNhapKho.setBackground(Color.decode("#55a996"));//thiet lap mau sac khi nhan vao
        btnXuatKho.setBackground(Color.decode("#FFFFFF"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNhapKho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXuatKho = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        layoutQuanLyHangTonKho = new javax.swing.JPanel();

        setBackground(new java.awt.Color(85, 169, 150));
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        setMaximumSize(new java.awt.Dimension(766, 640));
        setMinimumSize(new java.awt.Dimension(766, 640));
        setPreferredSize(new java.awt.Dimension(766, 640));

        jPanel1.setBackground(new java.awt.Color(85, 169, 150));
        jPanel1.setMaximumSize(new java.awt.Dimension(766, 70));
        jPanel1.setMinimumSize(new java.awt.Dimension(766, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 70));

        btnNhapKho.setBackground(new java.awt.Color(85, 169, 150));
        btnNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapKhoMouseClicked(evt);
            }
        });
        btnNhapKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Nhập Kho");
        btnNhapKho.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, 40));
        btnNhapKho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 70, 40));

        btnXuatKho.setBackground(new java.awt.Color(85, 169, 150));
        btnXuatKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatKhoMouseClicked(evt);
            }
        });
        btnXuatKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Xuất Kho");
        btnXuatKho.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 40));
        btnXuatKho.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 60, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNhapKho, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnXuatKho, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXuatKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhapKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layoutQuanLyHangTonKho.setBackground(new java.awt.Color(85, 169, 150));
        layoutQuanLyHangTonKho.setMaximumSize(new java.awt.Dimension(766, 570));
        layoutQuanLyHangTonKho.setMinimumSize(new java.awt.Dimension(766, 570));
        layoutQuanLyHangTonKho.setPreferredSize(new java.awt.Dimension(766, 570));

        javax.swing.GroupLayout layoutQuanLyHangTonKhoLayout = new javax.swing.GroupLayout(layoutQuanLyHangTonKho);
        layoutQuanLyHangTonKho.setLayout(layoutQuanLyHangTonKhoLayout);
        layoutQuanLyHangTonKhoLayout.setHorizontalGroup(
            layoutQuanLyHangTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layoutQuanLyHangTonKhoLayout.setVerticalGroup(
            layoutQuanLyHangTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layoutQuanLyHangTonKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(layoutQuanLyHangTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapKhoMouseClicked
   // Cai dathien thi cho nut NhapKho
        panelNhapKho.setVisible(true);
        panelXuatKho.setVisible(false);        
        btnXuatKho.setBackground(Color.decode("#FFFFFF"));
        btnNhapKho.setBackground(Color.decode("#55a996"));
    }//GEN-LAST:event_btnNhapKhoMouseClicked

    private void btnXuatKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatKhoMouseClicked
       // Cai dathien thi cho nut XuatKho
        panelXuatKho.setVisible(true);
        panelNhapKho.setVisible(false);
        btnXuatKho.setBackground(Color.decode("#55a996"));
        btnNhapKho.setBackground(Color.decode("#FFFFFF"));
        
    }//GEN-LAST:event_btnXuatKhoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnNhapKho;
    private javax.swing.JPanel btnXuatKho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel layoutQuanLyHangTonKho;
    // End of variables declaration//GEN-END:variables
}
