/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrame;

/**
 *
 * @author LOI LOI
 */
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

public class PanelBaoCaoHangTonKho extends javax.swing.JPanel {

    /**
     * Creates new form PanelBaoCaoHangTonKho
     */
    GridBagLayout layout=new GridBagLayout();
    PanelBaoCaoHangTonKho_BaoCao panelbaocao;
    
    public PanelBaoCaoHangTonKho() {
        
        initComponents();
        panelbaocao = new PanelBaoCaoHangTonKho_BaoCao();
        layoutBaoCaoHangTonKho.setLayout(layout);
        //them 2 panel vao grid
        GridBagConstraints grid=new GridBagConstraints();
        grid.gridx=0;
        grid.gridy=0;
        layoutBaoCaoHangTonKho.add(panelbaocao,grid);
        grid.gridx=0;
        grid.gridy=0;
        panelbaocao.setVisible(true);
        btnBaoCaoTongHopNhapXuatTon.setBackground(Color.decode("#FFFFFF"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBaoCaoTongHopNhapXuatTon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        layoutBaoCaoHangTonKho = new javax.swing.JPanel();

        setBackground(new java.awt.Color(85, 169, 150));
        setMaximumSize(new java.awt.Dimension(745, 630));
        setMinimumSize(new java.awt.Dimension(745, 630));

        btnBaoCaoTongHopNhapXuatTon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaoCaoTongHopNhapXuatTonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BÁO CÁO TỔNG HỢP NHẬP XUẤT TỒN");

        javax.swing.GroupLayout btnBaoCaoTongHopNhapXuatTonLayout = new javax.swing.GroupLayout(btnBaoCaoTongHopNhapXuatTon);
        btnBaoCaoTongHopNhapXuatTon.setLayout(btnBaoCaoTongHopNhapXuatTonLayout);
        btnBaoCaoTongHopNhapXuatTonLayout.setHorizontalGroup(
            btnBaoCaoTongHopNhapXuatTonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBaoCaoTongHopNhapXuatTonLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        btnBaoCaoTongHopNhapXuatTonLayout.setVerticalGroup(
            btnBaoCaoTongHopNhapXuatTonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBaoCaoTongHopNhapXuatTonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        layoutBaoCaoHangTonKho.setBackground(new java.awt.Color(85, 169, 150));

        javax.swing.GroupLayout layoutBaoCaoHangTonKhoLayout = new javax.swing.GroupLayout(layoutBaoCaoHangTonKho);
        layoutBaoCaoHangTonKho.setLayout(layoutBaoCaoHangTonKhoLayout);
        layoutBaoCaoHangTonKhoLayout.setHorizontalGroup(
            layoutBaoCaoHangTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        layoutBaoCaoHangTonKhoLayout.setVerticalGroup(
            layoutBaoCaoHangTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layoutBaoCaoHangTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBaoCaoTongHopNhapXuatTon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBaoCaoTongHopNhapXuatTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(layoutBaoCaoHangTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaoCaoTongHopNhapXuatTonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoCaoTongHopNhapXuatTonMouseClicked
// Cai dathien thi cho nut QUan ly san pham
        panelbaocao.setVisible(true);  
        btnBaoCaoTongHopNhapXuatTon.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_btnBaoCaoTongHopNhapXuatTonMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBaoCaoTongHopNhapXuatTon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel layoutBaoCaoHangTonKho;
    // End of variables declaration//GEN-END:variables
}
